/**
 * ASS Subtitle Generator with Rich Styling and Animation Tags
 * Phase 9: TASK-044
 *
 * Generates standards-compliant Advanced SubStation Alpha (.ass v4.00+) scripts
 * encoding typography, colors, borders, background boxes, entrance/exit motion,
 * and word-level karaoke timing for FFmpeg libass video burn-in and standalone players.
 */

import { SubtitleEvent, SubtitleStyle, AnimationConfig } from '../types/models.js';
import {
  DEFAULT_SCRIPT_RESOLUTION,
  ASS_STYLE_FORMAT_HEADER,
  colorToAss,
  getAssAlignment,
  calculateAssMarginV,
} from './assStyleSerializer.js';
import {
  compileAssTransitionTags,
  compileAssKaraokeText,
  formatAssTimestamp,
} from './animationEngine.js';

export interface AssScriptOptions {
  title?: string;
  playResX?: number;
  playResY?: number;
  includeKaraoke?: boolean;
  animationConfig?: AnimationConfig;
  styleName?: string;
  burnIn?: boolean;
}

/**
 * Convert Hex or CSS color to ASS override color tag \c&HBBGGRR& (and optional \1a&HAA&)
 */
function colorToAssOverrideTag(color: string, opacity: number = 1.0): string {
  const full = colorToAss(color, opacity);
  const hex = full.replace('&H', '');
  const alphaHex = hex.slice(0, 2);
  const bgrHex = hex.slice(2);
  let tag = `\\c&H${bgrHex}&`;
  if (alphaHex !== '00') {
    tag += `\\1a&H${alphaHex}&`;
  }
  return tag;
}

/**
 * Generate a complete, broadcast-quality ASS v4.00+ script string
 */
export function generateAssScript(
  events: SubtitleEvent[],
  style: SubtitleStyle,
  options: AssScriptOptions = {}
): string {
  const resX = options.playResX ?? DEFAULT_SCRIPT_RESOLUTION.playResX;
  const resY = options.playResY ?? DEFAULT_SCRIPT_RESOLUTION.playResY;
  const title = options.title || 'Vaani Studio Subtitles';
  const includeKaraoke = options.includeKaraoke !== false;
  const animConfig = options.animationConfig || style.animation;

  // 1. Script Info Section
  const scriptInfo = [
    '[Script Info]',
    `; Script generated by Vaani Studio - Local AI Subtitle Engine`,
    `Title: ${title.replace(/[\r\n]/g, ' ')}`,
    `ScriptType: v4.00+`,
    `WrapStyle: 0`,
    `ScaledBorderAndShadow: yes`,
    `YCbCr Matrix: TV.709`,
    `PlayResX: ${resX}`,
    `PlayResY: ${resY}`,
  ].join('\n');

  // 2. V4+ Styles Section
  const fontName = (style.fontFamily || 'Inter').split(',')[0].replace(/['"]/g, '').trim();
  const fontSize = Math.round(style.fontSize || 48);

  const baseColorAss = colorToAss(style.primaryColor, style.primaryOpacity ?? 1.0);
  const activeColorAss = colorToAss(style.activeWordColor || '#FFD700', 1.0);
  const strokeColorAss = colorToAss(style.strokeColor || '#000000', 1.0);

  let backColorAss: string;
  let outlineColorAss: string;
  let borderStyle = 1; // 1 = outline + drop shadow, 3 = opaque background box
  let outlineWidth = Math.round(style.strokeWidth ?? 0);
  let shadowDepth = Math.round(
    Math.max(style.shadowOffsetX ?? 0, style.shadowOffsetY ?? 0, style.shadowBlur ? style.shadowBlur / 3 : 0)
  );

  const hasBackgroundBox = Boolean(style.hasBackgroundBox && (style.backgroundOpacity ?? 0.8) > 0.05);

  if (hasBackgroundBox) {
    borderStyle = 3;
    // In ASS BorderStyle=3, OutlineColour is the background box fill color!
    outlineColorAss = colorToAss(style.backgroundColor || '#000000', style.backgroundOpacity ?? 0.8);
    outlineWidth = Math.round(Math.max(style.boxPaddingX ?? 10, style.boxPaddingY ?? 6) / 2);
    backColorAss = colorToAss(style.shadowColor || '#000000', 0.8);
    shadowDepth = 0;
  } else {
    borderStyle = 1;
    outlineColorAss = strokeColorAss;
    backColorAss = colorToAss(style.shadowColor || '#000000', 0.8);
  }

  const isBold =
    typeof style.fontWeight === 'number'
      ? style.fontWeight >= 700
        ? -1
        : 0
      : style.fontWeight === 'bold' || style.fontWeight === '800' || style.fontWeight === '900'
      ? -1
      : 0;

  const isItalic = style.fontStyle === 'italic' ? -1 : 0;
  const alignment = getAssAlignment(
    style.position?.alignment || 'center',
    style.position?.verticalPercent ?? 85
  );
  const marginV = calculateAssMarginV(style.position?.verticalPercent ?? 85, resY);
  const spacing = Math.round(style.letterSpacing ?? 0);

  // Standard style line: Primary = base text, Secondary = active highlight
  const defaultStyleLine = `Style: Default,${fontName},${fontSize},${baseColorAss},${activeColorAss},${outlineColorAss},${backColorAss},${isBold},${isItalic},0,0,100,100,${spacing},0,${borderStyle},${outlineWidth},${shadowDepth},${alignment},20,20,${marginV},1`;

  // Karaoke style line: In ASS karaoke (\k/\kf), SecondaryColour is the base color before highlight, and PrimaryColour is the highlighted fill
  const karaokeStyleLine = `Style: Karaoke,${fontName},${fontSize},${activeColorAss},${baseColorAss},${outlineColorAss},${backColorAss},${isBold},${isItalic},0,0,100,100,${spacing},0,${borderStyle},${outlineWidth},${shadowDepth},${alignment},20,20,${marginV},1`;

  const stylesSection = [
    '[V4+ Styles]',
    ASS_STYLE_FORMAT_HEADER,
    defaultStyleLine,
    karaokeStyleLine,
  ].join('\n');

  // 3. Events Section
  const eventsLines: string[] = [
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  // Sort events chronologically by startTime
  const sortedEvents = [...events].sort((a, b) => a.startTime - b.startTime);

  for (const ev of sortedEvents) {
    const hasWords = Boolean(ev.words && ev.words.length > 0);
    const isKaraoke = includeKaraoke && hasWords;

    // For video burn-in (or step karaoke mode when requested), slice dialogue lines
    // so only the currently spoken word is highlighted in activeWordColor,
    // matching KineticSubtitleRenderer precisely.
    if (options.burnIn && isKaraoke && animConfig?.karaokeMode !== 'sweep') {
      const words = ev.words!;
      const activeColorTag = colorToAssOverrideTag(style.activeWordColor || '#FACC15', 1.0);
      const baseColorTag = colorToAssOverrideTag(style.primaryColor || '#FFFFFF', style.primaryOpacity ?? 1.0);
      const scaleTag = animConfig?.activeWordEmphasis
        ? `\\fscx${Math.round((animConfig.activeWordScale || 1.08) * 100)}\\fscy${Math.round((animConfig.activeWordScale || 1.08) * 100)}`
        : '';
      const baseScaleTag = animConfig?.activeWordEmphasis ? '\\fscx100\\fscy100' : '';

      const formatLineWords = (activeIdx: number): string => {
        return words
          .map((w, idx) => {
            const punctuation = w.punctuationFollows || '';
            let wordText = `${w.word}${punctuation}`;
            if (style.textTransform === 'uppercase') {
              wordText = wordText.toUpperCase();
            } else if (style.textTransform === 'lowercase') {
              wordText = wordText.toLowerCase();
            }

            if (idx === activeIdx) {
              return `{${activeColorTag}${scaleTag}}${wordText}`;
            } else {
              return `{${baseColorTag}${baseScaleTag}}${wordText}`;
            }
          })
          .join(' ');
      };

      interface Slice {
        start: number;
        end: number;
        activeIdx: number;
      }
      const slices: Slice[] = [];

      // Pre-gap before first word
      if (words[0].startTime > ev.startTime + 0.01) {
        slices.push({ start: ev.startTime, end: words[0].startTime, activeIdx: -1 });
      }

      // Each word interval
      for (let i = 0; i < words.length; i++) {
        const w = words[i];
        if (w.endTime > w.startTime) {
          slices.push({ start: w.startTime, end: w.endTime, activeIdx: i });
        }

        if (i < words.length - 1) {
          const nextW = words[i + 1];
          if (nextW.startTime > w.endTime + 0.02) {
            slices.push({ start: w.endTime, end: nextW.startTime, activeIdx: -1 });
          }
        }
      }

      // Post-gap after last word
      const lastWord = words[words.length - 1];
      if (ev.endTime > lastWord.endTime + 0.01) {
        slices.push({ start: lastWord.endTime, end: ev.endTime, activeIdx: -1 });
      }

      if (slices.length === 0) {
        slices.push({ start: ev.startTime, end: ev.endTime, activeIdx: -1 });
      }

      for (let sIdx = 0; sIdx < slices.length; sIdx++) {
        const slice = slices[sIdx];
        const segStart = formatAssTimestamp(slice.start);
        const segEnd = formatAssTimestamp(slice.end);

        let phase: 'both' | 'entrance-only' | 'exit-only' | 'none';
        if (slices.length === 1) {
          phase = 'both';
        } else if (sIdx === 0) {
          phase = 'entrance-only';
        } else if (sIdx === slices.length - 1) {
          phase = 'exit-only';
        } else {
          phase = 'none';
        }

        const transTags = compileAssTransitionTags(animConfig, phase);
        const lineText = formatLineWords(slice.activeIdx);
        eventsLines.push(`Dialogue: 0,${segStart},${segEnd},Default,,0,0,0,,${transTags}${lineText}`);
      }
    } else {
      // Traditional karaoke or plain text
      const startAss = formatAssTimestamp(ev.startTime);
      const endAss = formatAssTimestamp(ev.endTime);
      const styleUsed = isKaraoke ? 'Karaoke' : 'Default';
      const transitionTags = compileAssTransitionTags(animConfig, 'both');

      let textPayload: string;
      if (isKaraoke) {
        textPayload = compileAssKaraokeText(ev, animConfig?.karaokeMode ?? 'step');
      } else {
        let plain = ev.text || '';
        if (style.textTransform === 'uppercase') {
          plain = plain.toUpperCase();
        } else if (style.textTransform === 'lowercase') {
          plain = plain.toLowerCase();
        }
        textPayload = plain.replace(/\r?\n/g, '\\N');
      }

      eventsLines.push(`Dialogue: 0,${startAss},${endAss},${styleUsed},,0,0,0,,${transitionTags}${textPayload}`);
    }
  }

  return `${scriptInfo}\n\n${stylesSection}\n\n${eventsLines.join('\n')}\n`;
}
