/**
 * ASS Subtitle Generator with Rich Styling and Animation Tags
 * Phase 9: TASK-044
 *
 * Generates standards-compliant Advanced SubStation Alpha (.ass v4.00+) scripts
 * encoding typography, colors, borders, background boxes, entrance/exit motion,
 * and word-level karaoke timing for FFmpeg libass video burn-in and standalone players.
 */

import { SubtitleEvent, SubtitleStyle, AnimationConfig } from '../types/models.js';
import {
  DEFAULT_SCRIPT_RESOLUTION,
  ASS_STYLE_FORMAT_HEADER,
  colorToAss,
  getAssAlignment,
  calculateAssMarginV,
} from './assStyleSerializer.js';
import {
  compileAssTransitionTags,
  compileAssKaraokeText,
  formatAssTimestamp,
} from './animationEngine.js';

export interface AssScriptOptions {
  title?: string;
  playResX?: number;
  playResY?: number;
  includeKaraoke?: boolean;
  animationConfig?: AnimationConfig;
  styleName?: string;
}

/**
 * Generate a complete, broadcast-quality ASS v4.00+ script string
 */
export function generateAssScript(
  events: SubtitleEvent[],
  style: SubtitleStyle,
  options: AssScriptOptions = {}
): string {
  const resX = options.playResX ?? DEFAULT_SCRIPT_RESOLUTION.playResX;
  const resY = options.playResY ?? DEFAULT_SCRIPT_RESOLUTION.playResY;
  const title = options.title || 'Vaani Studio Subtitles';
  const includeKaraoke = options.includeKaraoke !== false;
  const animConfig = options.animationConfig || style.animation;

  // 1. Script Info Section
  const scriptInfo = [
    '[Script Info]',
    `; Script generated by Vaani Studio - Local AI Subtitle Engine`,
    `Title: ${title.replace(/[\r\n]/g, ' ')}`,
    `ScriptType: v4.00+`,
    `WrapStyle: 0`,
    `ScaledBorderAndShadow: yes`,
    `YCbCr Matrix: TV.709`,
    `PlayResX: ${resX}`,
    `PlayResY: ${resY}`,
  ].join('\n');

  // 2. V4+ Styles Section
  // Build both 'Default' (normal text) and 'Karaoke' (where SecondaryColour is base and PrimaryColour is highlight)
  const fontName = (style.fontFamily || 'Inter').split(',')[0].replace(/['"]/g, '').trim();
  const fontSize = Math.round(style.fontSize || 48);

  const baseColorAss = colorToAss(style.primaryColor, style.primaryOpacity ?? 1.0);
  const activeColorAss = colorToAss(style.activeWordColor || '#FFD700', 1.0);
  const outlineColorAss = colorToAss(style.strokeColor || '#000000', 1.0);

  let backColorAss: string;
  let borderStyle = 1; // 1 = outline + drop shadow, 3 = opaque background box
  let outlineWidth = Math.round(style.strokeWidth ?? 0);
  let shadowDepth = Math.round(
    Math.max(style.shadowOffsetX ?? 0, style.shadowOffsetY ?? 0, style.shadowBlur ? style.shadowBlur / 3 : 0)
  );

  if (style.hasBackgroundBox) {
    borderStyle = 3;
    backColorAss = colorToAss(style.backgroundColor || '#000000', style.backgroundOpacity ?? 0.8);
    outlineWidth = Math.round(Math.max(style.boxPaddingX ?? 10, style.boxPaddingY ?? 6) / 2);
    shadowDepth = 0;
  } else {
    borderStyle = 1;
    backColorAss = colorToAss(style.shadowColor || '#000000', 0.8);
  }

  const isBold =
    typeof style.fontWeight === 'number'
      ? style.fontWeight >= 700
        ? -1
        : 0
      : style.fontWeight === 'bold' || style.fontWeight === '800' || style.fontWeight === '900'
      ? -1
      : 0;

  const isItalic = style.fontStyle === 'italic' ? -1 : 0;
  const alignment = getAssAlignment(
    style.position?.alignment || 'center',
    style.position?.verticalPercent ?? 85
  );
  const marginV = calculateAssMarginV(style.position?.verticalPercent ?? 85, resY);
  const spacing = Math.round(style.letterSpacing ?? 0);

  // Standard style line: Primary = base text, Secondary = active highlight
  const defaultStyleLine = `Style: Default,${fontName},${fontSize},${baseColorAss},${activeColorAss},${outlineColorAss},${backColorAss},${isBold},${isItalic},0,0,100,100,${spacing},0,${borderStyle},${outlineWidth},${shadowDepth},${alignment},20,20,${marginV},1`;

  // Karaoke style line: In ASS karaoke (\k/\kf), SecondaryColour is the base color before highlight, and PrimaryColour is the highlighted fill
  const karaokeStyleLine = `Style: Karaoke,${fontName},${fontSize},${activeColorAss},${baseColorAss},${outlineColorAss},${backColorAss},${isBold},${isItalic},0,0,100,100,${spacing},0,${borderStyle},${outlineWidth},${shadowDepth},${alignment},20,20,${marginV},1`;

  const stylesSection = [
    '[V4+ Styles]',
    ASS_STYLE_FORMAT_HEADER,
    defaultStyleLine,
    karaokeStyleLine,
  ].join('\n');

  // 3. Events Section
  const eventsLines: string[] = [
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  // Sort events chronologically by startTime
  const sortedEvents = [...events].sort((a, b) => a.startTime - b.startTime);

  for (const ev of sortedEvents) {
    const startAss = formatAssTimestamp(ev.startTime);
    const endAss = formatAssTimestamp(ev.endTime);

    const hasWords = Boolean(ev.words && ev.words.length > 0);
    const isKaraoke = includeKaraoke && hasWords;
    const styleUsed = isKaraoke ? 'Karaoke' : 'Default';

    // Transition tags
    const transitionTags = compileAssTransitionTags(animConfig);

    let textPayload: string;
    if (isKaraoke) {
      textPayload = compileAssKaraokeText(ev, animConfig?.karaokeMode ?? 'step');
    } else {
      textPayload = (ev.text || '').replace(/\r?\n/g, '\\N');
    }

    eventsLines.push(`Dialogue: 0,${startAss},${endAss},${styleUsed},,0,0,0,,${transitionTags}${textPayload}`);
  }

  return `${scriptInfo}\n\n${stylesSection}\n\n${eventsLines.join('\n')}\n`;
}
