/**
 * Default Built-in Professional Style Presets
 * Curated collection of broadcast-quality subtitle styling presets for Vaani Studio.
 */

import { StylePreset } from '../types/models.js';

export const BUILT_IN_PRESETS: StylePreset[] = [
  {
    id: 'preset_clean',
    name: 'Clean',
    description: 'Clear and modern. Good for most videos.',
    isBuiltIn: true,
    style: {
      id: 'style_clean',
      name: 'Clean',
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 48,
      fontWeight: 600,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.2,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FACC15', // Gold yellow highlight
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      boxPaddingX: 18,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_minimal',
    name: 'Minimal Pill',
    description: 'Simple and elegant.',
    isBuiltIn: true,
    style: {
      id: 'style_minimal',
      name: 'Minimal Pill',
      fontFamily: 'Roboto, system-ui, sans-serif',
      fontSize: 40,
      fontWeight: 600,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.35,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FACC15', // Amber active word
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'transparent',
      shadowBlur: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: true,
      backgroundColor: '#0F172A', // Slate dark
      backgroundOpacity: 0.85,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 10,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_podcast',
    name: 'Podcast Warm',
    description: 'Warm tones for interviews.',
    isBuiltIn: true,
    style: {
      id: 'style_podcast',
      name: 'Podcast Warm',
      fontFamily: 'Outfit, Inter, sans-serif',
      fontSize: 46,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.28,
      primaryColor: '#FDFBF7', // Cream warm white
      primaryOpacity: 1.0,
      activeWordColor: '#FB923C', // Warm orange
      strokeColor: '#1E1E1E',
      strokeWidth: 2,
      shadowColor: '#000000',
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 3,
      hasBackgroundBox: false,
      backgroundColor: '#1E1B18',
      backgroundOpacity: 0.8,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_karaoke',
    name: 'Karaoke Pop',
    description: 'Active word highlighting.',
    isBuiltIn: true,
    style: {
      id: 'style_karaoke',
      name: 'Karaoke Pop',
      fontFamily: 'Inter, Montserrat, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.25,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FFD700', // Vivid gold
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 1,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 82,
      },
    },
  },
  {
    id: 'preset_punch',
    name: 'Punch Reels',
    description: 'Bold and high contrast.',
    isBuiltIn: true,
    style: {
      id: 'style_punch',
      name: 'Punch Reels',
      fontFamily: 'Montserrat, Impact, sans-serif',
      fontSize: 54,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      lineHeight: 1.2,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FFE500', // Electric yellow
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: '#000000',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 3,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.8,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 78,
      },
    },
  },
  {
    id: 'preset_neon',
    name: 'Neon Glow',
    description: 'Modern and vibrant.',
    isBuiltIn: true,
    style: {
      id: 'style_neon',
      name: 'Neon Glow',
      fontFamily: 'Outfit, Montserrat, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 1.5,
      lineHeight: 1.25,
      primaryColor: '#E0FFFF', // Ice cyan
      primaryOpacity: 1.0,
      activeWordColor: '#FF007F', // Neon magenta
      strokeColor: '#0A0017', // Deep midnight purple
      strokeWidth: 3,
      shadowColor: '#00E5FF', // Vivid cyan glow
      shadowBlur: 18,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: false,
      backgroundColor: '#0A0A14',
      backgroundOpacity: 0.8,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_cinematic',
    name: 'Cinematic Serif',
    description: 'Film-style subtitles.',
    isBuiltIn: true,
    style: {
      id: 'style_cinematic',
      name: 'Cinematic Serif',
      fontFamily: 'Georgia, Merriweather, serif',
      fontSize: 42,
      fontWeight: 400,
      fontStyle: 'italic',
      textTransform: 'none',
      letterSpacing: 2.5,
      lineHeight: 1.4,
      primaryColor: '#FFFDF5', // Warm antique white
      primaryOpacity: 0.95,
      activeWordColor: '#F59E0B',
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 3,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 88,
      },
    },
  },
  {
    id: 'preset_news',
    name: 'News',
    description: 'Clean and professional.',
    isBuiltIn: true,
    style: {
      id: 'style_news',
      name: 'News',
      fontFamily: 'Inter, Arial, sans-serif',
      fontSize: 42,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.3,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: true,
      backgroundColor: '#002B49',
      backgroundOpacity: 0.9,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 88,
      },
    },
  },
  {
    id: 'preset_social',
    name: 'Social',
    description: 'Optimized for short-form content.',
    isBuiltIn: true,
    style: {
      id: 'style_social',
      name: 'Social',
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      lineHeight: 1.25,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 1,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.8,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 78,
      },
    },
  },
  {
    id: 'preset_documentary',
    name: 'Documentary',
    description: 'Subtle and unobtrusive.',
    isBuiltIn: true,
    style: {
      id: 'style_documentary',
      name: 'Documentary',
      fontFamily: 'Merriweather, Georgia, serif',
      fontSize: 40,
      fontWeight: 400,
      fontStyle: 'italic',
      textTransform: 'none',
      letterSpacing: 1.2,
      lineHeight: 1.35,
      primaryColor: '#F8FAFC',
      primaryOpacity: 0.95,
      activeWordColor: '#E2E8F0',
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 88,
      },
    },
  },
  {
    id: 'preset_classroom',
    name: 'Classroom',
    description: 'High readability.',
    isBuiltIn: true,
    style: {
      id: 'style_classroom',
      name: 'Classroom',
      fontFamily: 'Roboto, sans-serif',
      fontSize: 46,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0.4,
      lineHeight: 1.3,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'transparent',
      shadowBlur: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: true,
      backgroundColor: '#1E293B',
      backgroundOpacity: 0.88,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_mrbeast',
    name: 'MrBeast Bold',
    description: 'High-energy viral YouTube impact subtitles.',
    isBuiltIn: true,
    style: {
      id: 'style_mrbeast',
      name: 'MrBeast Bold',
      fontFamily: 'Montserrat, Impact, sans-serif',
      fontSize: 52,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      lineHeight: 1.2,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#22C55E', // Neon lime green
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: '#000000',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 3,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.8,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 80,
      },
    },
  },
  {
    id: 'preset_cyberpunk',
    name: 'Cyberpunk 2077',
    description: 'Futuristic synthwave neon cyan and hot pink.',
    isBuiltIn: true,
    style: {
      id: 'style_cyberpunk',
      name: 'Cyberpunk 2077',
      fontFamily: 'Outfit, Montserrat, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 1.5,
      lineHeight: 1.25,
      primaryColor: '#00F0FF', // Electric cyan
      primaryOpacity: 1.0,
      activeWordColor: '#FF007F', // Hot neon pink
      strokeColor: '#0B001A', // Midnight violet
      strokeWidth: 2.5,
      shadowColor: '#00F0FF',
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: true,
      backgroundColor: '#120826', // Deep neon purple box
      backgroundOpacity: 0.85,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_tiktok_fire',
    name: 'TikTok Fire',
    description: 'High-octane vertical short-form captions.',
    isBuiltIn: true,
    style: {
      id: 'style_tiktok_fire',
      name: 'TikTok Fire',
      fontFamily: 'Montserrat, Inter, sans-serif',
      fontSize: 50,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 1.0,
      lineHeight: 1.2,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#FF4500', // Fiery red-orange
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: true,
      backgroundColor: '#000000',
      backgroundOpacity: 0.85,
      boxPaddingX: 20,
      boxPaddingY: 8,
      boxBorderRadius: 16, // Pill shape
      position: {
        alignment: 'center',
        verticalPercent: 78,
      },
    },
  },
  {
    id: 'preset_comic_pop',
    name: 'Comic Pop',
    description: 'Expressive manga and anime subtitle typography.',
    isBuiltIn: true,
    style: {
      id: 'style_comic_pop',
      name: 'Comic Pop',
      fontFamily: 'Montserrat, sans-serif',
      fontSize: 48,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      lineHeight: 1.22,
      primaryColor: '#FEF08A', // Canary yellow
      primaryOpacity: 1.0,
      activeWordColor: '#F43F5E', // Rose magenta
      strokeColor: '#000000',
      strokeWidth: 4.5,
      shadowColor: '#000000',
      shadowBlur: 6,
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 82,
      },
    },
  },
  {
    id: 'preset_royal_gold',
    name: 'Royal Gold',
    description: 'Premium luxury and editorial video styling.',
    isBuiltIn: true,
    style: {
      id: 'style_royal_gold',
      name: 'Royal Gold',
      fontFamily: 'Georgia, serif',
      fontSize: 44,
      fontWeight: 600,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 2.0,
      lineHeight: 1.35,
      primaryColor: '#FFFBEB', // Pearl cream
      primaryOpacity: 1.0,
      activeWordColor: '#D97706', // Burnished gold
      strokeColor: '#1C1917',
      strokeWidth: 1.5,
      shadowColor: '#78350F',
      shadowBlur: 10,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.75,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 88,
      },
    },
  },
  {
    id: 'preset_vaporwave',
    name: 'Vaporwave',
    description: 'Dreamy 90s aesthetic with pastel violet and coral.',
    isBuiltIn: true,
    style: {
      id: 'style_vaporwave',
      name: 'Vaporwave',
      fontFamily: 'Outfit, Inter, sans-serif',
      fontSize: 46,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 1.8,
      lineHeight: 1.3,
      primaryColor: '#F3E8FF', // Lavender mist
      primaryOpacity: 1.0,
      activeWordColor: '#FB7185', // Coral rose
      strokeColor: '#1E1B4B', // Indigo stroke
      strokeWidth: 2,
      shadowColor: '#A855F7', // Violet glow
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: true,
      backgroundColor: '#1E1B4B',
      backgroundOpacity: 0.8,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_emerald',
    name: 'Emerald Glass',
    description: 'Modern corporate and tech presentation style.',
    isBuiltIn: true,
    style: {
      id: 'style_emerald',
      name: 'Emerald Glass',
      fontFamily: 'Inter, Roboto, sans-serif',
      fontSize: 44,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0.5,
      lineHeight: 1.3,
      primaryColor: '#F0FDF4', // Mint white
      primaryOpacity: 1.0,
      activeWordColor: '#10B981', // Vivid emerald green
      strokeColor: '#022C22',
      strokeWidth: 1,
      shadowColor: '#064E3B',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: true,
      backgroundColor: '#064E3B',
      backgroundOpacity: 0.85,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 86,
      },
    },
  },
  {
    id: 'preset_retro_vhs',
    name: 'Retro VHS',
    description: '80s analog tape video aesthetic.',
    isBuiltIn: true,
    style: {
      id: 'style_retro_vhs',
      name: 'Retro VHS',
      fontFamily: 'Courier New, monospace',
      fontSize: 42,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 2.0,
      lineHeight: 1.25,
      primaryColor: '#FDE047', // Phosphor yellow
      primaryOpacity: 1.0,
      activeWordColor: '#38BDF8', // Scanline cyan
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowBlur: 8,
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.8,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 84,
      },
    },
  },
  {
    id: 'preset_nordic_minimal',
    name: 'Nordic Minimal',
    description: 'Understated Scandinavian dark frosted glass pill.',
    isBuiltIn: true,
    style: {
      id: 'style_nordic_minimal',
      name: 'Nordic Minimal',
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 42,
      fontWeight: 500,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0.2,
      lineHeight: 1.3,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#60A5FA', // Glacier blue
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 1,
      hasBackgroundBox: true,
      backgroundColor: '#0F172A',
      backgroundOpacity: 0.65,
      boxPaddingX: 18,
      boxPaddingY: 8,
      boxBorderRadius: 12,
      position: {
        alignment: 'center',
        verticalPercent: 86,
      },
    },
  },
  {
    id: 'preset_crimson_rush',
    name: 'Crimson Rush',
    description: 'High-tension thriller and sports action styling.',
    isBuiltIn: true,
    style: {
      id: 'style_crimson_rush',
      name: 'Crimson Rush',
      fontFamily: 'Impact, Montserrat, sans-serif',
      fontSize: 52,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
      lineHeight: 1.2,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#EF4444', // Radiant crimson
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowColor: '#000000',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 3,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.8,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 80,
      },
    },
  },
  {
    id: 'preset_matrix_code',
    name: 'Matrix Code',
    description: 'Hacker terminal green monospace aesthetic.',
    isBuiltIn: true,
    style: {
      id: 'style_matrix_code',
      name: 'Matrix Code',
      fontFamily: 'Courier New, monospace',
      fontSize: 44,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 1.0,
      lineHeight: 1.25,
      primaryColor: '#4ADE80', // Terminal phosphor green
      primaryOpacity: 1.0,
      activeWordColor: '#FFFFFF', // Blinking cursor white
      strokeColor: '#052E16',
      strokeWidth: 2,
      shadowColor: '#22C55E',
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      hasBackgroundBox: true,
      backgroundColor: '#022C22',
      backgroundOpacity: 0.9,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 4,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
  {
    id: 'preset_sunset_blaze',
    name: 'Sunset Blaze',
    description: 'Warm golden hour and travel vlog style.',
    isBuiltIn: true,
    style: {
      id: 'style_sunset_blaze',
      name: 'Sunset Blaze',
      fontFamily: 'Montserrat, Outfit, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      lineHeight: 1.25,
      primaryColor: '#FFF7ED', // Warm sunlight cream
      primaryOpacity: 1.0,
      activeWordColor: '#EA580C', // Deep sunset orange
      strokeColor: '#2A0800',
      strokeWidth: 3,
      shadowColor: '#C2410C',
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.75,
      boxPaddingX: 16,
      boxPaddingY: 8,
      boxBorderRadius: 8,
      position: {
        alignment: 'center',
        verticalPercent: 82,
      },
    },
  },
  {
    id: 'preset_custom1',
    name: 'Custom 1',
    description: 'Your custom style.',
    isBuiltIn: true,
    style: {
      id: 'style_custom1',
      name: 'Custom 1',
      fontFamily: 'Inter, sans-serif',
      fontSize: 44,
      fontWeight: 600,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      lineHeight: 1.3,
      primaryColor: '#FFFFFF',
      primaryOpacity: 1.0,
      activeWordColor: '#60A5FA',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      hasBackgroundBox: false,
      backgroundColor: '#000000',
      backgroundOpacity: 0.7,
      boxPaddingX: 14,
      boxPaddingY: 6,
      boxBorderRadius: 6,
      position: {
        alignment: 'center',
        verticalPercent: 85,
      },
    },
  },
];

/**
 * Get built-in preset by ID
 */
export function getBuiltInPreset(id: string): StylePreset | undefined {
  return BUILT_IN_PRESETS.find((p) => p.id === id);
}

/**
 * Default fallback subtitle style (Clean preset)
 */
export const DEFAULT_SUBTITLE_STYLE = BUILT_IN_PRESETS[0].style;
